{% set name = "cached-property" %}
{% set version = "1.5.1" %}
{% set sha256 = "9217a59f14a5682da7c4b8829deadbfc194ac22e9908ccf7c8820234e80a1504" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - cached_property

about:
  home: https://github.com/pydanny/cached-property
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A decorator for caching properties in classes.'
  description: |
    Cached-property is a decorator for caching properties in classes. It
    makes caching of time or computational expensive properties quick and easy.
  doc_url: https://pypi.python.org/pypi/cached-property
  dev_url: https://github.com/pydanny/cached-property
  doc_source_url: https://github.com/pydanny/cached-property/blob/master/README.rst

extra:
  recipe-maintainers:
    - mvdbeek
